// <auto-generated />
using System;
using Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191112013410_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedIn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnName("EMAIL")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnName("MESSAGE")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnName("NAME")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnName("PHONE_NUMBER")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnName("SUBJECT")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TB_CONTACT");
                });

            modelBuilder.Entity("Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnName("ACTIVE")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedIn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnName("CODE")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Default")
                        .HasColumnName("DEFAULT")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .HasColumnName("IMAGE")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Loaded")
                        .HasColumnName("LOADED")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnName("NAME")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TB_LANGUAGE");
                });

            modelBuilder.Entity("Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedIn")
                        .HasColumnType("TEXT");

                    b.Property<string>("CPF")
                        .HasColumnName("CPF")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnName("DATA_NASCIMENTO")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnName("EMAIL")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnName("NOME")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnName("TELEFONE")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TB_PERSON");
                });
#pragma warning restore 612, 618
        }
    }
}
